/*
 * This file was automatically generated by wupf@
 * Thu Nov 28 11:45:53 GMT 2019
 */

package org.jpf.utils.ios;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class JpfOsUtil_WETest {

	@Test(timeout = 1000)
	public void testGetOsName() throws Throwable {
		String string0 = JpfOsUtil.getOsName();
		assertEquals("Windows 10", string0);
	}

	@Test(timeout = 1000)
	public void testIsWindows() throws Throwable {
		boolean boolean0 = JpfOsUtil.isWindows();
		assertTrue(boolean0);
	}

	@Test(timeout = 3000)
	public void testGetLocalIP() throws Throwable {
		String string0 = JpfOsUtil.getLocalIP();
		assertEquals("127.0.0.1", string0);
	}

}
