/*
 * This file was automatically generated by wupf@
 * Thu Nov 28 12:22:56 GMT 2019
 */

package org.jpf.utils.web;

import static org.junit.Assert.fail;
import static org.junit.Assert.assertNotSame;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertNull;

import java.awt.HeadlessException;

import org.junit.Test;

public class BrowerOpenWork_WETest {

	@Test(timeout = 1000)
	public void testOpenWebUrl() throws Throwable {
		new JpfBrowerOpenWork().openWebUrl("file:///f7le:.//@e2BCbKAct']");
	}

	@Test(timeout = 1000)
	public void testOpenWebUrlThrowsHeadlessException() throws Throwable {
		// Undeclared exception!
		try {
			new JpfBrowerOpenWork().openWebUrl("/");

		} catch (HeadlessException e) {
			//
			// no message in exception (getMessage() returned null)
			//
		}
	}

	@Test(timeout = 1000)
	public void testOpenWebUrlThrowsNullPointerException() throws Throwable {
		// Undeclared exception!
		try {
			new JpfBrowerOpenWork().openWebUrl((String) null);

		} catch (NullPointerException e) {
			//
			// no message in exception (getMessage() returned null)
			//
		}
	}

	/**
	 * Run the void openWebUrl(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy wupf at 20-5-7 上午10:15
	 */
	@Test
	public void testOpenWebUrl_1() throws Exception {
		String strUrl = "";

		new JpfBrowerOpenWork().openWebUrl(strUrl);

		// add additional test code here
	}

}
