/*
 * This file was automatically generated by wupf@
 * Thu Nov 28 11:22:13 GMT 2019
 */

package org.jpf.utils.encrypts;

import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

import org.junit.Test;

public class CryptoUtil_WETest {

	@Test(timeout = 1000)
	public void testMain() throws Throwable {
		String Encryptstr = CryptoUtil.Encrypt("blade@37.132", CryptoUtil.AES_KEY);
		System.out.println("加密后密码: " + Encryptstr);
		System.out.println("解密后密码：" + CryptoUtil.Decrypt(Encryptstr, CryptoUtil.AES_KEY));
		String Decryptstr = CryptoUtil.Decrypt("CsZfRchu1CHa3x19vsvNBA", CryptoUtil.AES_KEY);
		System.out.println("解密后密码：" + Decryptstr);
	}

	@Test(timeout = 1000)
	public void testEncryptWithNullAndNonEmptyString0() throws Throwable {
		String string0 = CryptoUtil.Encrypt("bladtestcloudaes", (String) null);
		assertNull(string0);
	}

	@Test(timeout = 1000)
	public void testEncrypt() throws Throwable {
		String string0 = CryptoUtil.Encrypt("utf-8", "utf-8");
		assertNull(string0);
	}

	@Test(timeout = 1000)
	public void testDecryptWithNullAndNull() throws Throwable {
		String string0 = CryptoUtil.Decrypt((String) null, (String) null);
		assertNull(string0);
	}

	@Test(timeout = 1000)
	public void testEncryptReturningNonEmptyString() throws Throwable {
		String string0 = CryptoUtil.Encrypt("utf-8", "bladtestcloudaes");
		assertNotEquals("xZgBatyANiV0sAjiyhd_mA\r\n", string0);
		assertNotNull(string0);
	}

	@Test(timeout = 1000)
	public void testDecryptWithNonEmptyString() throws Throwable {
		String string0 = CryptoUtil.Decrypt("bladtestcloudaes", "bladtestcloudaes");
		assertNull(string0);
	}

	@Test(timeout = 1000)
	public void testEncryptWithNullAndNonEmptyString1() throws Throwable {
		String string0 = CryptoUtil.Encrypt((String) null, "bladtestcloudaes");
		assertNull(string0);
	}

	@Test(timeout = 1000)
	public void testEncryptWithEmptyString() throws Throwable {
		String string0 = CryptoUtil.Encrypt("", "1]WcTNV}OjQ6uNn8B9d");
		assertNull(string0);
	}

	@Test(timeout = 1000)
	public void testDecryptWithEmptyString() throws Throwable {
		String string0 = CryptoUtil.Decrypt("", "AES/ECB/PKCS5Padding");
		assertNull(string0);
	}
}
