/*
 * This file was automatically generated by wupf@
 * Thu Nov 28 11:25:07 GMT 2019
 */

package org.jpf.utils.encrypts;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import org.junit.Test;

import com.alibaba.fastjson.JSON;

public class JpfMD5EncryptionUtil_WPTest {

	/**
	 * Run the getEncryption method test.
	 *
	 * @throws Exception
	 * 
	 * @generatedBy wupf @2019-11-28 19:22:49
	 * @see public static String getEncryption(String originString)
	 */
	@Test(timeout = 1000)
	public void test_getEncryption_R4() throws Throwable {

		String originString = "中文";

		String wupf_result = JpfMD5EncryptionUtil.getEncryption(originString);

		System.out.println("jpf_check:getEncryption:" + JSON.toJSONString(wupf_result));
		assertNotNull(JSON.toJSONString(wupf_result));

	}

	@Test(timeout = 1000)
	public void testGetEncryptionReturningEmptyString() throws Throwable {
		String string0 = JpfMD5EncryptionUtil.getEncryption((String) null);
		assertEquals("", string0);
	}

	@Test(timeout = 1000)
	public void testGetEncryptionReturningNonEmptyString() throws Throwable {
		String string0 = JpfMD5EncryptionUtil.getEncryption("");
		assertEquals("D41D8CD98F0FB24FE9809F98ECF8427E", string0);
	}
}
