/*
 * This file was automatically generated by wupf@
 * Thu Nov 28 11:27:25 GMT 2019
 */

package org.jpf.utils.encrypts;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import org.junit.Test;

public class MD5Filter_WPTest {

	@Test(timeout = 1000)
	public void testGetMd5ByStringReturningEmptyString() throws Throwable {
		String string0 = MD5Filter.getMd5ByString((String) null);
		assertNotNull(string0);
		assertEquals("", string0);
	}

	
}
