/*
 * This file was automatically generated by wupf@
 * Thu Nov 28 11:26:56 GMT 2019
 */

package org.jpf.utils.encrypts;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class MD6Util_WETest {

	@Test(timeout = 1000)
	public void testMd6() throws Throwable {
		String string0 = MD6Util.md6("4F(HzV`Ou'\" `D");
		assertNotEquals("00cd968666b4c077978d890c276479cf", string0);
	}

	@Test(timeout = 1000)
	public void testIsEqualWithNull() throws Throwable {
		boolean boolean0 = MD6Util.isEqual((String) null, "00cd968666b4c077978d890c276479cf");
		assertFalse(boolean0);
	}

	@Test(timeout = 1000)
	public void testIsEqualReturningTrue() throws Throwable {
		boolean boolean0 = MD6Util.isEqual("00cd968666b4c077978d890c276479cf", "4F(HzV`Ou'\" `D");
		assertTrue(boolean0);
	}

	@Test(timeout = 1000)
	public void testIsEqualReturningFalse() throws Throwable {
		boolean boolean0 = MD6Util.isEqual("R+3TZsCRDNl8]m", "0088c72820fd7a59827eff788745ed0a");
		assertFalse(boolean0);
	}

	@Test(timeout = 1000)
	public void testIsEqualWithNonEmptyString0() throws Throwable {
		boolean boolean0 = MD6Util.isEqual("0088c72820fd7a59827eff788745ed0a", "qzN:AJ*");
		assertFalse(boolean0);
	}

}
