/*
 * This file was automatically generated by         wupf
 * Thu Nov 28 11:32:49 GMT 2019
 */

package org.jpf.utils.encrypts;

import static org.junit.Assert.fail;

import java.security.InvalidParameterException;

import org.junit.Test;

public class RSAUtil_WPTest {

	@Test(timeout = 1000)
	public void testGetPublicKeyTakingStringReturningNull() throws Throwable {
		String string0 = "";
		RSAUtil.getPublicKey("");
		String string1 = null;
		// Undeclared exception!
		try {
			RSAUtil.decryptString((String) null, (String) null);
			fail("Expecting exception: NullPointerException");

		} catch (NullPointerException e) {
			//
			// no message in exception (getMessage() returned null)
			//
		}
		
	}

	@Test(timeout = 1000)
	public void testGenerateKeyPairThrowsInvalidParameterException() throws Throwable {
		String string0 = "So!p|TpE)1%@|V(";
		RSAUtil.getPrivateKey("So!p|TpE)1%@|V(");
		int int0 = 0;
		// Undeclared exception!
		try {
			RSAUtil.generateKeyPair(0);
			fail("Expecting exception: InvalidParameterException");

		} catch (InvalidParameterException e) {
		}
	}



	@Test(timeout = 1000)
	public void testEncryptStringThrowsRuntimeException() throws Throwable {
		int int0 = 9;
		RSAUtil.createKeys(9);
		String string0 = "com.google.common.collect.FilteredEntryMultimap$AsMap";
		String string1 = "com.google.common.cache.AbstractCache";
		try {
			RSAUtil.encryptString("com.google.common.collect.FilteredEntryMultimap$AsMap",
					"com.google.common.cache.AbstractCache");
			fail("Expecting exception: RuntimeException");

		} catch (RuntimeException e) {
			//
			// An exception occurred while encrypting the string [com.google.common.collect.FilteredEntryMultimap$AsMap]
			//
		}
	}


}
