/*
 * This file was automatically generated by wupf@
 * Thu Nov 28 11:13:18 GMT 2019
 */

package org.jpf.utils.conf;

import org.junit.Test;
import static org.junit.Assert.assertNotSame;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.*;
import java.io.IOException;
import org.jpf.utils.conf.JpfHashIni;

public class JpfHashIni_WETest {

	@Test(timeout = 1000)
	public void testSetValue() throws Throwable {
		JpfHashIni.setValue("com.google.common.base.CharMatcher$Or", "B. ]piLM0UJ<d2",
				"com.google.common.base.CharMatcher$Or");
	}

	@Test(timeout = 1000)
	public void testGetValueReturningNull() throws Throwable {
		Object object0 = JpfHashIni.getValue("|", "S@avm6ea$Yg`ZL:Ss3");
		assertNull(object0);
	}

	@Test(timeout = 1000)
	public void testGetValueReturningNonNull() throws Throwable {
		Object object0 = JpfHashIni.getValue("com.google.common.base.CharMatcher$Or", "");
		assertNull(object0);
	}

	@Test(timeout = 1000)
	public void testWriteIniWithNull() throws Throwable {
		try {
			JpfHashIni.writeIni((String) null);
			fail("Expecting exception: IOException");

		} catch (IOException e) {
			//
			// no file name given
			//
		}
	}

}
