/*
 * This file was automatically generated by wupf@
 * Thu Nov 28 11:15:23 GMT 2019
 */

package org.jpf.utils.conf;

import static org.junit.Assert.fail;

import org.junit.Test;

public class JpfPropertiesUtil_WPTest {

	@Test(timeout = 1000)
	public void testKeyThrowsIllegalArgumentException() throws Throwable {
		// Undeclared exception!
		try {
			JpfPropertiesUtil.key("");
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
		}
	}

	@Test(timeout = 1000)
	public void testKeyThrowsNullPointerException() throws Throwable {
		// Undeclared exception!
		try {
			JpfPropertiesUtil.key((String) null);
			fail("Expecting exception: NullPointerException");

		} catch (NullPointerException e) {
		}
	}

}
