/*
 * This file was automatically generated by wupf@
 * Thu Nov 28 11:14:11 GMT 2019
 */

package org.jpf.utils.conf;

import static org.junit.Assert.assertNull;
import static org.junit.Assert.fail;

import java.io.FileNotFoundException;

import org.junit.Test;

public class JpfPropertiesUtil_WETest {

	@Test(timeout = 1000)
	public void testKeyReturningNull() throws Throwable {
		String string0 = JpfPropertiesUtil.key("H]7Z9ML m|/=T0_@1X");
		assertNull(string0);
	}

	@Test(timeout = 1000)
	public void testGetAllPropertiesThrowsFileNotFoundException() throws Throwable {
		try {
			JpfPropertiesUtil.GetAllProperties("V%u@%+");
			fail("Expecting exception: FileNotFoundException");

		} catch (FileNotFoundException e) {
			//
			// no message in exception (getMessage() returned null)
			//
		}
	}

	@Test(timeout = 1000)
	public void testGetAllPropertiesThrowsNullPointerException() throws Throwable {
		// Undeclared exception!
		try {
			JpfPropertiesUtil.GetAllProperties((String) null);
			fail("Expecting exception: NullPointerException");

		} catch (NullPointerException e) {
			//
			// no message in exception (getMessage() returned null)
			//
		}
	}

	@Test(timeout = 1000)
	public void testWritePropertiesThrowsNullPointerException() throws Throwable {
		// Undeclared exception!
		try {
			JpfPropertiesUtil.WriteProperties((String) null, (String) null, "");
			fail("Expecting exception: NullPointerException");

		} catch (NullPointerException e) {
			//
			// no message in exception (getMessage() returned null)
			//
		}
	}

	@Test(timeout = 1000)
	public void testKeyThrowsIllegalArgumentException() throws Throwable {
		// Undeclared exception!
		try {
			JpfPropertiesUtil.key("");
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
		}
	}

	@Test(timeout = 1000)
	public void testKeyThrowsNullPointerException() throws Throwable {
		// Undeclared exception!
		try {
			JpfPropertiesUtil.key((String) null);
			fail("Expecting exception: NullPointerException");

		} catch (NullPointerException e) {
		}
	}

	@Test(timeout = 1000)
	public void testGetValueByKeyReturningNull() throws Throwable {
		String string0 = JpfPropertiesUtil.GetValueByKey("H]7Z9ML m|/=T0_@1X", "{9~q/.;>G+8]w>KB;");
		assertNull(string0);
	}

}
