/*
 * This file was automatically generated by wupf@
 * Thu Nov 28 11:17:34 GMT 2019
 */

package org.jpf.utils.dbsql;

import static org.junit.Assert.assertNotNull;

import org.junit.Test;

public class AppConn_WPTest {

	
	@Test(timeout = 1000)
	public void testGetInstance() throws Throwable {
		AppConn appConn0 = AppConn.getInstance();
		assertNotNull(appConn0);
	}
}
