/*
 * This file was automatically generated by wupf@
 * Thu Nov 28 11:15:32 GMT 2019
 */

package org.jpf.utils.dbsql;

import org.junit.Test;
import static org.junit.Assert.*;
import org.jpf.utils.dbsql.DbErrorCodeInfo;

public class DbErrorCodeInfo_WETest {

	@Test(timeout = 1000)
	public void testCreatesDbErrorCodeInfo() throws Throwable {
		DbErrorCodeInfo dbErrorCodeInfo0 = new DbErrorCodeInfo();
		assertEquals((-4), DbErrorCodeInfo.REQUEST_FAIL_SQL_DELETE);
	}
}
