/*
 * This file was automatically generated by wupf@
 * Thu Nov 28 11:16:51 GMT 2019
 */

package org.jpf.utils.dbsql;

import org.junit.Test;

public class DbInfoWork_WETest {

	@Test(timeout = 1000)
	public void testCreatesDbInfoUtils() throws Throwable {
		DbInfoWork dbInfoUtils0 = new DbInfoWork();
	}



}
