/*
 * This file was automatically generated by wupf@
 * Thu Nov 28 10:56:07 GMT 2019
 */

package org.jpf.algorithm;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import org.junit.Test;

public class Kmp_WETest {


	@Test(timeout = 1000)
	public void testNext0() throws Throwable {
		char[] charArray0 = new char[5];
		int[] intArray0 =new Kmp().next(charArray0);

		assertArrayEquals(new int[] { (-1), (-1), (-1), (-1), (-1) }, intArray0);
	}

	@Test(timeout = 1000)
	public void testNext1() throws Throwable {
		char[] charArray0 = new char[5];
		charArray0[0] = '>';
		int[] intArray0 = new Kmp().next(charArray0);
		assertArrayEquals(new int[] { (-1), 0, 0, 0, 0 }, intArray0);
	}

	@Test(timeout = 1000)
	public void testKMP_Index0() throws Throwable {
		char[] charArray0 = new char[5];
		char[] charArray1 = new char[1];
		int int0 = new Kmp().KMP_Index(charArray0, charArray1);
		assertEquals(0, int0);
	}

	@Test(timeout = 1000)
	public void testKMP_Index1() throws Throwable {
		char[] charArray0 = new char[5];
		int int0 = new Kmp().KMP_Index(charArray0, charArray0);
		assertEquals(0, int0);
	}

	@Test(timeout = 1000)
	public void testKMP_IndexReturningPositive() throws Throwable {
		char[] charArray0 = new char[2];
		charArray0[0] = '{';
		char[] charArray1 = new char[1];
		int int0 = new Kmp().KMP_Index(charArray0, charArray1);
		assertEquals(1, int0);
	}

	@Test(timeout = 1000)
	public void testKMP_IndexReturningNegative() throws Throwable {
		char[] charArray0 = new char[5];
		char[] charArray1 = new char[1];
		int int0 = new Kmp().KMP_Index(charArray1, charArray0);
		assertEquals((-1), int0);
	}

	@Test(timeout = 1000)
	public void testKMP_IndexThrowsArrayIndexOutOfBoundsException() throws Throwable {
		char[] charArray0 = new char[0];
		// Undeclared exception!
		try {
			new Kmp().KMP_Index(charArray0, charArray0);
			fail("Expecting exception: ArrayIndexOutOfBoundsException");

		} catch (ArrayIndexOutOfBoundsException e) {
			//
			// 0
			//
		}
	}

	@Test(timeout = 1000)
	public void testKMP_IndexThrowsNullPointerException() throws Throwable {
		// Undeclared exception!
		try {
			new Kmp().KMP_Index((char[]) null, (char[]) null);
			fail("Expecting exception: NullPointerException");

		} catch (NullPointerException e) {
			//
			// no message in exception (getMessage() returned null)
			//
		}
	}

	@Test(timeout = 1000)
	public void testNextThrowsArrayIndexOutOfBoundsException() throws Throwable {
		char[] charArray0 = new char[0];
		// Undeclared exception!
		try {
			new Kmp().next(charArray0);
			fail("Expecting exception: ArrayIndexOutOfBoundsException");

		} catch (ArrayIndexOutOfBoundsException e) {
			//
			// 0
			//
		}
	}

	@Test(timeout = 1000)
	public void testNextThrowsNullPointerException() throws Throwable {
		// Undeclared exception!
		try {
			new Kmp().next((char[]) null);
			fail("Expecting exception: NullPointerException");

		} catch (NullPointerException e) {

		}
	}
}
