/*
 * This file was automatically generated by wupf@
 * Thu Nov 28 10:58:35 GMT 2019
 */

package org.jpf.algorithm;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import org.junit.Test;

public class LevenshteinDistance_WETest {

	@Test(timeout = 1000)
	public void testCreatesLevenshteinDistance() throws Throwable {
		LevenshteinDistance levenshteinDistance0 = new LevenshteinDistance();
	}

	@Test(timeout = 1000)
	public void testGetSimilarityRatioWithEmptyStringAndNonEmptyString0() throws Throwable {
		float float0 = new LevenshteinDistance().getSimilarityRatio("", "U~\"\",Ab");
		assertEquals(0.0F, float0, 0.01F);
	}

	@Test(timeout = 1000)
	public void testGetSimilarityRatioWithEmptyStringAndNonEmptyString1() throws Throwable {
		float float0 = new LevenshteinDistance().getSimilarityRatio("U~\"\",Ab", "");
		assertEquals(0.0F, float0, 0.01F);
	}

	@Test(timeout = 1000)
	public void testGetSimilarityRatioThrowsNullPointerException() throws Throwable {
		// Undeclared exception!
		try {
			new LevenshteinDistance().getSimilarityRatio((String) null, "P.0G|yq_X*_C");
			fail("Expecting exception: NullPointerException");

		} catch (NullPointerException e) {
			//
			// no message in exception (getMessage() returned null)
			//
		}
	}

	@Test(timeout = 1000)
	public void testGetSimilarityRatioReturningPositive() throws Throwable {
		float float0 = new LevenshteinDistance().getSimilarityRatio("kJ", "kJ");
		assertEquals(1.0F, float0, 0.01F);
	}
}
