/*
 * This file was automatically generated by wupf@
 * Thu Nov 28 11:06:46 GMT 2019
 */

package org.jpf.mlgb;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class Mlgbz_WETest {

	@Test(timeout = 3000)
	public void testMlgbz1() throws Throwable {
		Mlgbz mlgbz0 = new Mlgbz();
		boolean boolean0 = mlgbz0.mlgbz1();
		assertTrue(boolean0);
	}

}
