/*
 * This file was automatically generated by wupf@
 * Thu Nov 28 11:50:52 GMT 2019
 */

package org.jpf.utils;

import static org.junit.Assert.fail;

import javax.servlet.http.HttpServletRequest;

import org.junit.Test;

public class JpfIpUtil_WPTest {



	@Test(timeout = 1000)
	public void testGetIpAddrThrowsNullPointerException() throws Throwable {
		// Undeclared exception!
		try {
			JpfIpUtil.getIpAddr((HttpServletRequest) null);
			fail("Expecting exception: NullPointerException");

		} catch (NullPointerException e) {
			//
			// no message in exception (getMessage() returned null)
			//
		}
	}
}
