/*
 * This file was automatically generated by         
 * Thu Nov 28 12:01:16 GMT 2019
 */

package org.jpf.utils;

import static org.junit.Assert.fail;

import java.io.DataOutputStream;
import java.io.FileDescriptor;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PipedOutputStream;
import java.io.SyncFailedException;

import org.jpf.utils.JvmUtil;
import org.junit.Test;

public class JVMUtil_WETest {


	@Test(timeout = 1000)
	public void testJstackThrowsNullPointerException() throws Throwable {
		JvmUtil jVMUtil0 = new JvmUtil();
		String string0 = "L8>3 VB!Q";
		String string1 = " (suspended)";
		DataOutputStream dataOutputStream0 = new DataOutputStream((OutputStream) null);
		try {
			new JvmUtil().jstack(dataOutputStream0);
			fail("Expecting exception: NullPointerException");

		} catch (NullPointerException e) {
			//
			// no message in exception (getMessage() returned null)
			//
		}
	}

	@Test(timeout = 1000)
	public void test1() throws Throwable {
		FileDescriptor fileDescriptor0 = new FileDescriptor();
		try {
			fileDescriptor0.sync();
			fail("Expecting exception: SyncFailedException");

		} catch (SyncFailedException e) {
			//
			// sync failed
			//
		}
	}

	@Test(timeout = 1000)
	public void testJstackThrowsIOException() throws Throwable {
		PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
		try {
			new JvmUtil().jstack(pipedOutputStream0);
			fail("Expecting exception: IOException");

		} catch (IOException e) {
			//
			// Pipe not connected
			//
		}
	}


   
    
	/**
	* Run the jstack method test.
	*
	* @throws Exception
	* 
	* @generatedBy  
	* @2019-11-28 19:58:40
	* @see public static  void jstack(OutputStream stream) throws Exception  
	*/
	@Test(timeout = 1000)
	public void test_jstack_R0() throws Throwable {

		try {

			OutputStream stream = null;

			new JvmUtil().jstack(stream);


		} catch (Exception ex) {
			ex.printStackTrace();
		}

	}
}
